spring.application.name=novashop

spring.datasource.url=${DB_URL}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.username=${DB_USERNAME}
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000


spring.jpa.hibernate.ddl-auto=update
spring.main.banner-mode=off
spring.jpa.show-sql=true
logging.file.name=logs/novashop.log
logging.level.sql=info
logging.level.root=info
logging.level.com.bastug.novashop=debug
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql=trace
logging.level.org.springframework.security=debug

